/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Tyvox API
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from "./fetch-wrapper";
export type CheckASRReadiness200 = {
  ready: boolean;
  error?: string;
};

export type ListASRModels200ItemModelSelection =
  (typeof ListASRModels200ItemModelSelection)[keyof typeof ListASRModels200ItemModelSelection];

export const ListASRModels200ItemModelSelection = {
  fixed: "fixed",
  custom: "custom",
} as const;

export type ListASRModels200ItemModelsItemStatus =
  (typeof ListASRModels200ItemModelsItemStatus)[keyof typeof ListASRModels200ItemModelsItemStatus];

export const ListASRModels200ItemModelsItemStatus = {
  not_ready: "not_ready",
  preparing: "preparing",
  ready: "ready",
  error: "error",
} as const;

export type ListASRModels200ItemModelsItem = {
  id: string;
  name: string;
  status: ListASRModels200ItemModelsItemStatus;
  /**
   * @minimum 0
   * @maximum 1
   */
  progress?: number;
  error?: string;
};

export type ListASRModels200Item = {
  id: string;
  name: string;
  modelSelection: ListASRModels200ItemModelSelection;
  models: ListASRModels200ItemModelsItem[];
};

export type PrepareASRModel404Error = {
  code: string;
  message: string;
};

export type PrepareASRModel404 = {
  error: PrepareASRModel404Error;
};

export type SendTranscribeChunk200 = {
  receivedBytes: number;
};

export type FinalizeTranscribe200 = {
  text: string;
  language?: string;
  durationMs: number;
};

export type FinalizeTranscribe404Error = {
  code: string;
  message: string;
};

export type FinalizeTranscribe404 = {
  error: FinalizeTranscribe404Error;
};

export type TransformTextBodyEnrichOptionsItem = {
  type: "translate";
  payload: {
    target: string;
  };
};

export type TransformTextBody = {
  /** @minLength 1 */
  text: string;
  enrichOptions: TransformTextBodyEnrichOptionsItem[];
  /**
   * @minimum 1
   * @maximum 5
   */
  timeoutScale?: number;
};

export type TransformText200 =
  | {
      event: "thinking";
      data: { [key: string]: unknown };
    }
  | {
      event: "chunk";
      data: {
        text: string;
      };
    }
  | {
      event: "done";
      data: {
        text: string;
      };
    }
  | {
      event: "error";
      data: {
        code: string;
        message: string;
      };
    };

export type TransformText400Error = {
  code: string;
  message: string;
};

export type TransformText400 = {
  error: TransformText400Error;
};

export type GetVocabulary200Vocabulary = { [key: string]: number };

export type GetVocabulary200 = {
  vocabulary: GetVocabulary200Vocabulary;
};

export type RenameEntryBody = {
  /** @minLength 1 */
  newEntry: string;
};

export type RenameEntry400Error = {
  code: string;
  message: string;
};

export type RenameEntry400 = {
  error: RenameEntry400Error;
};

export type GetUserConfig200Version =
  (typeof GetUserConfig200Version)[keyof typeof GetUserConfig200Version];

export const GetUserConfig200Version = {
  NUMBER_1: 1,
} as const;

export type GetUserConfig200DesktopHotkeyMode =
  (typeof GetUserConfig200DesktopHotkeyMode)[keyof typeof GetUserConfig200DesktopHotkeyMode];

export const GetUserConfig200DesktopHotkeyMode = {
  ptt: "ptt",
  toggle: "toggle",
} as const;

export type GetUserConfig200DesktopHotkey = {
  mode: GetUserConfig200DesktopHotkeyMode;
};

export type GetUserConfig200DesktopActionsBasicHotkey = {
  accelerator: string;
};

export type GetUserConfig200DesktopActionsBasic = {
  hotkey: GetUserConfig200DesktopActionsBasicHotkey;
};

export type GetUserConfig200DesktopActionsTranslateHotkey = {
  accelerator: string;
};

export type GetUserConfig200DesktopActionsTranslatePayload = {
  target: string;
};

export type GetUserConfig200DesktopActionsTranslate = {
  hotkey: GetUserConfig200DesktopActionsTranslateHotkey;
  payload: GetUserConfig200DesktopActionsTranslatePayload;
};

export type GetUserConfig200DesktopActions = {
  basic: GetUserConfig200DesktopActionsBasic;
  translate: GetUserConfig200DesktopActionsTranslate;
};

export type GetUserConfig200DesktopMicrophone = {
  deviceId: string;
};

export type GetUserConfig200DesktopUiLocale =
  (typeof GetUserConfig200DesktopUiLocale)[keyof typeof GetUserConfig200DesktopUiLocale];

export const GetUserConfig200DesktopUiLocale = {
  en: "en",
  zh: "zh",
} as const;

export type GetUserConfig200Desktop = {
  hotkey: GetUserConfig200DesktopHotkey;
  actions: GetUserConfig200DesktopActions;
  microphone: GetUserConfig200DesktopMicrophone;
  uiLocale: GetUserConfig200DesktopUiLocale;
};

export type GetUserConfig200LlmProvider =
  (typeof GetUserConfig200LlmProvider)[keyof typeof GetUserConfig200LlmProvider];

export const GetUserConfig200LlmProvider = {
  ark: "ark",
  deepseek: "deepseek",
  siliconflow: "siliconflow",
  openai: "openai",
  openrouter: "openrouter",
  minimax: "minimax",
  stepfun: "stepfun",
  dashscope: "dashscope",
  zhipu: "zhipu",
  moonshot: "moonshot",
  "kimi-for-coding": "kimi-for-coding",
  ollama: "ollama",
  gemini: "gemini",
  groq: "groq",
  custom: "custom",
} as const;

export type GetUserConfig200LlmTone =
  (typeof GetUserConfig200LlmTone)[keyof typeof GetUserConfig200LlmTone];

export const GetUserConfig200LlmTone = {
  professional: "professional",
  casual: "casual",
  concise: "concise",
  formal: "formal",
} as const;

export type GetUserConfig200Llm = {
  provider: GetUserConfig200LlmProvider;
  apiKey: string;
  baseUrl: string;
  model: string;
  tone: GetUserConfig200LlmTone;
  thinkingEnabled?: boolean;
  extraBody?: string;
};

export type GetUserConfig200SpeechProvider =
  (typeof GetUserConfig200SpeechProvider)[keyof typeof GetUserConfig200SpeechProvider];

export const GetUserConfig200SpeechProvider = {
  "whisper:small": "whisper:small",
  "whisper:medium": "whisper:medium",
  "whisper:large-v3": "whisper:large-v3",
  "sensevoice:small": "sensevoice:small",
} as const;

export type GetUserConfig200Speech = {
  provider: GetUserConfig200SpeechProvider;
  apiKey?: string;
  url?: string;
  /** @maxItems 3 */
  languages: string[];
};

export type GetUserConfig200 = {
  version: GetUserConfig200Version;
  desktop: GetUserConfig200Desktop;
  llm: GetUserConfig200Llm;
  speech: GetUserConfig200Speech;
};

export type UpdateUserConfigBodyVersion =
  (typeof UpdateUserConfigBodyVersion)[keyof typeof UpdateUserConfigBodyVersion];

export const UpdateUserConfigBodyVersion = {
  NUMBER_1: 1,
} as const;

export type UpdateUserConfigBodyDesktopHotkeyMode =
  (typeof UpdateUserConfigBodyDesktopHotkeyMode)[keyof typeof UpdateUserConfigBodyDesktopHotkeyMode];

export const UpdateUserConfigBodyDesktopHotkeyMode = {
  ptt: "ptt",
  toggle: "toggle",
} as const;

export type UpdateUserConfigBodyDesktopHotkey = {
  mode?: UpdateUserConfigBodyDesktopHotkeyMode;
};

export type UpdateUserConfigBodyDesktopActionsBasicHotkey = {
  accelerator?: string;
};

export type UpdateUserConfigBodyDesktopActionsBasic = {
  hotkey?: UpdateUserConfigBodyDesktopActionsBasicHotkey;
};

export type UpdateUserConfigBodyDesktopActionsTranslateHotkey = {
  accelerator?: string;
};

export type UpdateUserConfigBodyDesktopActionsTranslatePayload = {
  target?: string;
};

export type UpdateUserConfigBodyDesktopActionsTranslate = {
  hotkey?: UpdateUserConfigBodyDesktopActionsTranslateHotkey;
  payload?: UpdateUserConfigBodyDesktopActionsTranslatePayload;
};

export type UpdateUserConfigBodyDesktopActions = {
  basic?: UpdateUserConfigBodyDesktopActionsBasic;
  translate?: UpdateUserConfigBodyDesktopActionsTranslate;
};

export type UpdateUserConfigBodyDesktopMicrophone = {
  deviceId?: string;
};

export type UpdateUserConfigBodyDesktopUiLocale =
  (typeof UpdateUserConfigBodyDesktopUiLocale)[keyof typeof UpdateUserConfigBodyDesktopUiLocale];

export const UpdateUserConfigBodyDesktopUiLocale = {
  en: "en",
  zh: "zh",
} as const;

export type UpdateUserConfigBodyDesktop = {
  hotkey?: UpdateUserConfigBodyDesktopHotkey;
  actions?: UpdateUserConfigBodyDesktopActions;
  microphone?: UpdateUserConfigBodyDesktopMicrophone;
  uiLocale?: UpdateUserConfigBodyDesktopUiLocale;
};

export type UpdateUserConfigBodyLlmProvider =
  (typeof UpdateUserConfigBodyLlmProvider)[keyof typeof UpdateUserConfigBodyLlmProvider];

export const UpdateUserConfigBodyLlmProvider = {
  ark: "ark",
  deepseek: "deepseek",
  siliconflow: "siliconflow",
  openai: "openai",
  openrouter: "openrouter",
  minimax: "minimax",
  stepfun: "stepfun",
  dashscope: "dashscope",
  zhipu: "zhipu",
  moonshot: "moonshot",
  "kimi-for-coding": "kimi-for-coding",
  ollama: "ollama",
  gemini: "gemini",
  groq: "groq",
  custom: "custom",
} as const;

export type UpdateUserConfigBodyLlmTone =
  (typeof UpdateUserConfigBodyLlmTone)[keyof typeof UpdateUserConfigBodyLlmTone];

export const UpdateUserConfigBodyLlmTone = {
  professional: "professional",
  casual: "casual",
  concise: "concise",
  formal: "formal",
} as const;

export type UpdateUserConfigBodyLlm = {
  provider?: UpdateUserConfigBodyLlmProvider;
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  tone?: UpdateUserConfigBodyLlmTone;
  thinkingEnabled?: boolean;
  extraBody?: string;
};

export type UpdateUserConfigBodySpeechProvider =
  (typeof UpdateUserConfigBodySpeechProvider)[keyof typeof UpdateUserConfigBodySpeechProvider];

export const UpdateUserConfigBodySpeechProvider = {
  "whisper:small": "whisper:small",
  "whisper:medium": "whisper:medium",
  "whisper:large-v3": "whisper:large-v3",
  "sensevoice:small": "sensevoice:small",
} as const;

export type UpdateUserConfigBodySpeech = {
  provider?: UpdateUserConfigBodySpeechProvider;
  apiKey?: string;
  url?: string;
  /** @maxItems 3 */
  languages?: string[];
};

export type UpdateUserConfigBody = {
  version?: UpdateUserConfigBodyVersion;
  desktop?: UpdateUserConfigBodyDesktop;
  llm?: UpdateUserConfigBodyLlm;
  speech?: UpdateUserConfigBodySpeech;
};

export type UpdateUserConfig200Version =
  (typeof UpdateUserConfig200Version)[keyof typeof UpdateUserConfig200Version];

export const UpdateUserConfig200Version = {
  NUMBER_1: 1,
} as const;

export type UpdateUserConfig200DesktopHotkeyMode =
  (typeof UpdateUserConfig200DesktopHotkeyMode)[keyof typeof UpdateUserConfig200DesktopHotkeyMode];

export const UpdateUserConfig200DesktopHotkeyMode = {
  ptt: "ptt",
  toggle: "toggle",
} as const;

export type UpdateUserConfig200DesktopHotkey = {
  mode: UpdateUserConfig200DesktopHotkeyMode;
};

export type UpdateUserConfig200DesktopActionsBasicHotkey = {
  accelerator: string;
};

export type UpdateUserConfig200DesktopActionsBasic = {
  hotkey: UpdateUserConfig200DesktopActionsBasicHotkey;
};

export type UpdateUserConfig200DesktopActionsTranslateHotkey = {
  accelerator: string;
};

export type UpdateUserConfig200DesktopActionsTranslatePayload = {
  target: string;
};

export type UpdateUserConfig200DesktopActionsTranslate = {
  hotkey: UpdateUserConfig200DesktopActionsTranslateHotkey;
  payload: UpdateUserConfig200DesktopActionsTranslatePayload;
};

export type UpdateUserConfig200DesktopActions = {
  basic: UpdateUserConfig200DesktopActionsBasic;
  translate: UpdateUserConfig200DesktopActionsTranslate;
};

export type UpdateUserConfig200DesktopMicrophone = {
  deviceId: string;
};

export type UpdateUserConfig200DesktopUiLocale =
  (typeof UpdateUserConfig200DesktopUiLocale)[keyof typeof UpdateUserConfig200DesktopUiLocale];

export const UpdateUserConfig200DesktopUiLocale = {
  en: "en",
  zh: "zh",
} as const;

export type UpdateUserConfig200Desktop = {
  hotkey: UpdateUserConfig200DesktopHotkey;
  actions: UpdateUserConfig200DesktopActions;
  microphone: UpdateUserConfig200DesktopMicrophone;
  uiLocale: UpdateUserConfig200DesktopUiLocale;
};

export type UpdateUserConfig200LlmProvider =
  (typeof UpdateUserConfig200LlmProvider)[keyof typeof UpdateUserConfig200LlmProvider];

export const UpdateUserConfig200LlmProvider = {
  ark: "ark",
  deepseek: "deepseek",
  siliconflow: "siliconflow",
  openai: "openai",
  openrouter: "openrouter",
  minimax: "minimax",
  stepfun: "stepfun",
  dashscope: "dashscope",
  zhipu: "zhipu",
  moonshot: "moonshot",
  "kimi-for-coding": "kimi-for-coding",
  ollama: "ollama",
  gemini: "gemini",
  groq: "groq",
  custom: "custom",
} as const;

export type UpdateUserConfig200LlmTone =
  (typeof UpdateUserConfig200LlmTone)[keyof typeof UpdateUserConfig200LlmTone];

export const UpdateUserConfig200LlmTone = {
  professional: "professional",
  casual: "casual",
  concise: "concise",
  formal: "formal",
} as const;

export type UpdateUserConfig200Llm = {
  provider: UpdateUserConfig200LlmProvider;
  apiKey: string;
  baseUrl: string;
  model: string;
  tone: UpdateUserConfig200LlmTone;
  thinkingEnabled?: boolean;
  extraBody?: string;
};

export type UpdateUserConfig200SpeechProvider =
  (typeof UpdateUserConfig200SpeechProvider)[keyof typeof UpdateUserConfig200SpeechProvider];

export const UpdateUserConfig200SpeechProvider = {
  "whisper:small": "whisper:small",
  "whisper:medium": "whisper:medium",
  "whisper:large-v3": "whisper:large-v3",
  "sensevoice:small": "sensevoice:small",
} as const;

export type UpdateUserConfig200Speech = {
  provider: UpdateUserConfig200SpeechProvider;
  apiKey?: string;
  url?: string;
  /** @maxItems 3 */
  languages: string[];
};

export type UpdateUserConfig200 = {
  version: UpdateUserConfig200Version;
  desktop: UpdateUserConfig200Desktop;
  llm: UpdateUserConfig200Llm;
  speech: UpdateUserConfig200Speech;
};

export type PostClientLogsBodyEntriesItemLevel =
  (typeof PostClientLogsBodyEntriesItemLevel)[keyof typeof PostClientLogsBodyEntriesItemLevel];

export const PostClientLogsBodyEntriesItemLevel = {
  debug: "debug",
  info: "info",
  warn: "warn",
  error: "error",
} as const;

export type PostClientLogsBodyEntriesItemExtra = { [key: string]: unknown };

export type PostClientLogsBodyEntriesItem = {
  level: PostClientLogsBodyEntriesItemLevel;
  message: string;
  sessionId?: string;
  stack?: string;
  extra?: PostClientLogsBodyEntriesItemExtra;
};

export type PostClientLogsBody = {
  /** @maxItems 50 */
  entries: PostClientLogsBodyEntriesItem[];
};

export type PostClientLogs200 = {
  received: number;
};

export type PostClientLogs400Error = {
  code: string;
  message: string;
};

export type PostClientLogs400 = {
  error: PostClientLogs400Error;
};

export type ListLLMProviders200ItemId =
  (typeof ListLLMProviders200ItemId)[keyof typeof ListLLMProviders200ItemId];

export const ListLLMProviders200ItemId = {
  ark: "ark",
  deepseek: "deepseek",
  siliconflow: "siliconflow",
  openai: "openai",
  openrouter: "openrouter",
  minimax: "minimax",
  stepfun: "stepfun",
  dashscope: "dashscope",
  zhipu: "zhipu",
  moonshot: "moonshot",
  "kimi-for-coding": "kimi-for-coding",
  ollama: "ollama",
  gemini: "gemini",
  groq: "groq",
  custom: "custom",
} as const;

export type ListLLMProviders200Item = {
  id: ListLLMProviders200ItemId;
  name: string;
  defaultBaseUrl: string;
};

export type CheckLLMReadiness200 = {
  ready: boolean;
  error?: string;
};

export type HealthCheck200 = {
  status: string;
  version: string;
};

export type CheckASRReadinessResponseOk = {
  data: CheckASRReadiness200;
  status: 200;
};

export type CheckASRReadinessResponseSuccess = CheckASRReadinessResponseOk & {
  headers: Headers;
};

export type CheckASRReadinessResponse = CheckASRReadinessResponseSuccess;

export const getCheckASRReadinessUrl = () => {
  return `/api/asr/readiness`;
};

/**
 * @summary Check ASR provider readiness
 */
export const checkASRReadiness = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<CheckASRReadinessResponse> => {
  return customFetch<CheckASRReadinessResponse>(getCheckASRReadinessUrl(), {
    ...options,
    method: "GET",
  });
};

export type ListASRModelsResponseOk = {
  data: ListASRModels200Item[];
  status: 200;
};

export type ListASRModelsResponseSuccess = ListASRModelsResponseOk & {
  headers: Headers;
};

export type ListASRModelsResponse = ListASRModelsResponseSuccess;

export const getListASRModelsUrl = () => {
  return `/api/asr/models`;
};

/**
 * @summary List ASR providers and model statuses
 */
export const listASRModels = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ListASRModelsResponse> => {
  return customFetch<ListASRModelsResponse>(getListASRModelsUrl(), {
    ...options,
    method: "GET",
  });
};

export type PrepareASRModelResponseOk = {
  data: void;
  status: 200;
};

export type PrepareASRModelResponseNotFound = {
  data: PrepareASRModel404;
  status: 404;
};

export type PrepareASRModelResponseSuccess = PrepareASRModelResponseOk & {
  headers: Headers;
};
export type PrepareASRModelResponseError = PrepareASRModelResponseNotFound & {
  headers: Headers;
};

export type PrepareASRModelResponse = PrepareASRModelResponseSuccess | PrepareASRModelResponseError;

export const getPrepareASRModelUrl = (id: string) => {
  return `/api/asr/models/${id}/prepare`;
};

/**
 * @summary Prepare an ASR model
 */
export const prepareASRModel = async (
  id: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<PrepareASRModelResponse> => {
  return customFetch<PrepareASRModelResponse>(getPrepareASRModelUrl(id), {
    ...options,
    method: "POST",
  });
};

export type SendTranscribeChunkResponseOk = {
  data: SendTranscribeChunk200;
  status: 200;
};

export type SendTranscribeChunkResponseSuccess = SendTranscribeChunkResponseOk & {
  headers: Headers;
};

export type SendTranscribeChunkResponse = SendTranscribeChunkResponseSuccess;

export const getSendTranscribeChunkUrl = (sessionId: string) => {
  return `/api/asr/transcribe/${sessionId}/chunk`;
};

/**
 * @summary Upload audio chunk during recording
 */
export const sendTranscribeChunk = async (
  sessionId: string,
  sendTranscribeChunkBody: Blob,
  options?: Parameters<typeof customFetch>[1],
): Promise<SendTranscribeChunkResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<SendTranscribeChunkResponse>(getSendTranscribeChunkUrl(sessionId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "audio/pcm", ...getHeaders(options?.headers) },
    body: sendTranscribeChunkBody,
  });
};

export type FinalizeTranscribeResponseOk = {
  data: FinalizeTranscribe200;
  status: 200;
};

export type FinalizeTranscribeResponseNotFound = {
  data: FinalizeTranscribe404;
  status: 404;
};

export type FinalizeTranscribeResponseSuccess = FinalizeTranscribeResponseOk & {
  headers: Headers;
};
export type FinalizeTranscribeResponseError = FinalizeTranscribeResponseNotFound & {
  headers: Headers;
};

export type FinalizeTranscribeResponse =
  | FinalizeTranscribeResponseSuccess
  | FinalizeTranscribeResponseError;

export const getFinalizeTranscribeUrl = (sessionId: string) => {
  return `/api/asr/transcribe/${sessionId}/finalize`;
};

/**
 * @summary Finalize recording and run ASR
 */
export const finalizeTranscribe = async (
  sessionId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<FinalizeTranscribeResponse> => {
  return customFetch<FinalizeTranscribeResponse>(getFinalizeTranscribeUrl(sessionId), {
    ...options,
    method: "POST",
  });
};

export const getTransformTextUrl = () => {
  return `/api/transform`;
};

/**
 * @summary Transform text: polish, translate, or enrich (SSE streaming)
 */
export const transformText = async (
  transformTextBody: TransformTextBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<Response> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<Response>(getTransformTextUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(transformTextBody),
  });
};

export type GetVocabularyResponseOk = {
  data: GetVocabulary200;
  status: 200;
};

export type GetVocabularyResponseSuccess = GetVocabularyResponseOk & {
  headers: Headers;
};

export type GetVocabularyResponse = GetVocabularyResponseSuccess;

export const getGetVocabularyUrl = () => {
  return `/api/vocabulary`;
};

/**
 * @summary Get user vocabulary
 */
export const getVocabulary = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<GetVocabularyResponse> => {
  return customFetch<GetVocabularyResponse>(getGetVocabularyUrl(), {
    ...options,
    method: "GET",
  });
};

export type ClearVocabularyResponseOk = {
  data: void;
  status: 200;
};

export type ClearVocabularyResponseSuccess = ClearVocabularyResponseOk & {
  headers: Headers;
};

export type ClearVocabularyResponse = ClearVocabularyResponseSuccess;

export const getClearVocabularyUrl = () => {
  return `/api/vocabulary`;
};

/**
 * @summary Clear all vocabulary
 */
export const clearVocabulary = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ClearVocabularyResponse> => {
  return customFetch<ClearVocabularyResponse>(getClearVocabularyUrl(), {
    ...options,
    method: "DELETE",
  });
};

export type AddEntryResponseOk = {
  data: void;
  status: 200;
};

export type AddEntryResponseSuccess = AddEntryResponseOk & {
  headers: Headers;
};

export type AddEntryResponse = AddEntryResponseSuccess;

export const getAddEntryUrl = (entry: string) => {
  return `/api/vocabulary/vocabulary/${entry}`;
};

/**
 * @summary Add vocabulary entry
 */
export const addEntry = async (
  entry: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<AddEntryResponse> => {
  return customFetch<AddEntryResponse>(getAddEntryUrl(entry), {
    ...options,
    method: "POST",
  });
};

export type DeleteEntryResponseOk = {
  data: void;
  status: 200;
};

export type DeleteEntryResponseSuccess = DeleteEntryResponseOk & {
  headers: Headers;
};

export type DeleteEntryResponse = DeleteEntryResponseSuccess;

export const getDeleteEntryUrl = (entry: string) => {
  return `/api/vocabulary/vocabulary/${entry}`;
};

/**
 * @summary Delete vocabulary entry
 */
export const deleteEntry = async (
  entry: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<DeleteEntryResponse> => {
  return customFetch<DeleteEntryResponse>(getDeleteEntryUrl(entry), {
    ...options,
    method: "DELETE",
  });
};

export type RenameEntryResponseOk = {
  data: void;
  status: 200;
};

export type RenameEntryResponseBadRequest = {
  data: RenameEntry400;
  status: 400;
};

export type RenameEntryResponseSuccess = RenameEntryResponseOk & {
  headers: Headers;
};
export type RenameEntryResponseError = RenameEntryResponseBadRequest & {
  headers: Headers;
};

export type RenameEntryResponse = RenameEntryResponseSuccess | RenameEntryResponseError;

export const getRenameEntryUrl = (entry: string) => {
  return `/api/vocabulary/vocabulary/${entry}/rename`;
};

/**
 * @summary Rename vocabulary entry
 */
export const renameEntry = async (
  entry: string,
  renameEntryBody: RenameEntryBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<RenameEntryResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<RenameEntryResponse>(getRenameEntryUrl(entry), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(renameEntryBody),
  });
};

export type GetUserConfigResponseOk = {
  data: GetUserConfig200;
  status: 200;
};

export type GetUserConfigResponseSuccess = GetUserConfigResponseOk & {
  headers: Headers;
};

export type GetUserConfigResponse = GetUserConfigResponseSuccess;

export const getGetUserConfigUrl = () => {
  return `/api/user_config`;
};

/**
 * @summary Get user config
 */
export const getUserConfig = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<GetUserConfigResponse> => {
  return customFetch<GetUserConfigResponse>(getGetUserConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export type UpdateUserConfigResponseOk = {
  data: UpdateUserConfig200;
  status: 200;
};

export type UpdateUserConfigResponseSuccess = UpdateUserConfigResponseOk & {
  headers: Headers;
};

export type UpdateUserConfigResponse = UpdateUserConfigResponseSuccess;

export const getUpdateUserConfigUrl = () => {
  return `/api/user_config`;
};

/**
 * @summary Update user config (partial merge)
 */
export const updateUserConfig = async (
  updateUserConfigBody: UpdateUserConfigBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<UpdateUserConfigResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<UpdateUserConfigResponse>(getUpdateUserConfigUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(updateUserConfigBody),
  });
};

export type PostClientLogsResponseOk = {
  data: PostClientLogs200;
  status: 200;
};

export type PostClientLogsResponseBadRequest = {
  data: PostClientLogs400;
  status: 400;
};

export type PostClientLogsResponseSuccess = PostClientLogsResponseOk & {
  headers: Headers;
};
export type PostClientLogsResponseError = PostClientLogsResponseBadRequest & {
  headers: Headers;
};

export type PostClientLogsResponse = PostClientLogsResponseSuccess | PostClientLogsResponseError;

export const getPostClientLogsUrl = () => {
  return `/api/logs`;
};

/**
 * @summary Upload client log entries
 */
export const postClientLogs = async (
  postClientLogsBody: PostClientLogsBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<PostClientLogsResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<PostClientLogsResponse>(getPostClientLogsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(postClientLogsBody),
  });
};

export type ListLLMProvidersResponseOk = {
  data: ListLLMProviders200Item[];
  status: 200;
};

export type ListLLMProvidersResponseSuccess = ListLLMProvidersResponseOk & {
  headers: Headers;
};

export type ListLLMProvidersResponse = ListLLMProvidersResponseSuccess;

export const getListLLMProvidersUrl = () => {
  return `/api/llm/providers`;
};

/**
 * @summary List supported LLM providers
 */
export const listLLMProviders = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ListLLMProvidersResponse> => {
  return customFetch<ListLLMProvidersResponse>(getListLLMProvidersUrl(), {
    ...options,
    method: "GET",
  });
};

export type CheckLLMReadinessResponseOk = {
  data: CheckLLMReadiness200;
  status: 200;
};

export type CheckLLMReadinessResponseSuccess = CheckLLMReadinessResponseOk & {
  headers: Headers;
};

export type CheckLLMReadinessResponse = CheckLLMReadinessResponseSuccess;

export const getCheckLLMReadinessUrl = () => {
  return `/api/llm/readiness`;
};

/**
 * @summary Check LLM provider readiness
 */
export const checkLLMReadiness = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<CheckLLMReadinessResponse> => {
  return customFetch<CheckLLMReadinessResponse>(getCheckLLMReadinessUrl(), {
    ...options,
    method: "GET",
  });
};

export type HealthCheckResponseOk = {
  data: HealthCheck200;
  status: 200;
};

export type HealthCheckResponseSuccess = HealthCheckResponseOk & {
  headers: Headers;
};

export type HealthCheckResponse = HealthCheckResponseSuccess;

export const getHealthCheckUrl = () => {
  return `/health`;
};

/**
 * @summary Health check
 */
export const healthCheck = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<HealthCheckResponse> => {
  return customFetch<HealthCheckResponse>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};
